"""Demo recipes, inserted once when the collection is empty."""

from .models import Ingredient, RecipeCreate

DEMO_RECIPES: list[RecipeCreate] = [
    RecipeCreate(
        name="Gratin dauphinois",
        type="Plat",
        category="Hiver",
        servings=4,
        prep_minutes=20,
        cook_minutes=60,
        temperature="Chaud",
        favorite=True,
        ingredients=[
            Ingredient(name="Pommes de terre", quantity=1, unit="kg"),
            Ingredient(name="Crème liquide", quantity=40, unit="cl"),
            Ingredient(name="Lait", quantity=20, unit="cl"),
            Ingredient(name="Ail", quantity=2, unit="gousses"),
            Ingredient(name="Noix de muscade", quantity=1, unit="pincée"),
        ],
        steps=[
            "Préchauffer le four à 160 °C.",
            "Éplucher et couper les pommes de terre en fines rondelles.",
            "Frotter le plat avec une gousse d'ail, puis beurrer.",
            "Disposer les rondelles en couches, saler et poivrer.",
            "Verser le mélange lait-crème et la muscade, cuire 1 h.",
        ],
        notes="Ne pas rincer les pommes de terre : l'amidon lie le gratin.",
    ),
    RecipeCreate(
        name="Salade de lentilles au chèvre",
        type="Entrée",
        category="Été",
        servings=2,
        prep_minutes=15,
        cook_minutes=25,
        temperature="Froid",
        ingredients=[
            Ingredient(name="Lentilles vertes", quantity=150, unit="g"),
            Ingredient(name="Fromage de chèvre", quantity=100, unit="g"),
            Ingredient(name="Échalote", quantity=1, unit="u."),
            Ingredient(name="Huile d'olive", quantity=2, unit="c.à.s"),
            Ingredient(name="Vinaigre balsamique", quantity=1, unit="c.à.s"),
            Ingredient(name="Persil", quantity=1, unit="bouquet"),
        ],
        steps=[
            "Cuire les lentilles 25 min dans l'eau non salée, puis égoutter.",
            "Émincer l'échalote et ciseler le persil.",
            "Mélanger huile et vinaigre, saler, poivrer.",
            "Assembler tiède, ajouter le chèvre émietté au moment de servir.",
        ],
    ),
    RecipeCreate(
        name="Mousse au chocolat",
        type="Dessert",
        category="Franchouillard",
        servings=6,
        prep_minutes=20,
        cook_minutes=0,
        temperature="Froid",
        favorite=True,
        ingredients=[
            Ingredient(name="Chocolat noir", quantity=200, unit="g"),
            Ingredient(name="Oeufs", quantity=6, unit="u."),
            Ingredient(name="Sucre", quantity=30, unit="g"),
            Ingredient(name="Sel", quantity=1, unit="pincée"),
        ],
        steps=[
            "Faire fondre le chocolat au bain-marie, laisser tiédir.",
            "Séparer les blancs des jaunes, incorporer les jaunes au chocolat.",
            "Monter les blancs en neige avec le sel, serrer avec le sucre.",
            "Incorporer délicatement en trois fois, réfrigérer 4 h minimum.",
        ],
        notes="Le chocolat doit être tiède, sinon il fige au contact des blancs.",
    ),
    RecipeCreate(
        name="Poulet au curry et lait de coco",
        type="Plat",
        category="Asiatique",
        servings=4,
        prep_minutes=15,
        cook_minutes=30,
        temperature="Chaud",
        ingredients=[
            Ingredient(name="Blancs de poulet", quantity=600, unit="g"),
            Ingredient(name="Lait de coco", quantity=40, unit="cl"),
            Ingredient(name="Oignon", quantity=1, unit="u."),
            Ingredient(name="Curry", quantity=2, unit="c.à.c"),
            Ingredient(name="Riz basmati", quantity=300, unit="g"),
            Ingredient(name="Gingembre", quantity=1, unit="c.à.c"),
        ],
        steps=[
            "Couper le poulet en cubes, émincer l'oignon.",
            "Faire revenir l'oignon, ajouter le poulet et colorer.",
            "Ajouter curry et gingembre, puis le lait de coco.",
            "Laisser mijoter 25 min à feu doux, servir avec le riz.",
        ],
    ),
    RecipeCreate(
        name="Vinaigrette maison",
        type="Sauce/Base",
        category="Franchouillard",
        servings=8,
        prep_minutes=5,
        cook_minutes=0,
        temperature="Froid",
        ingredients=[
            Ingredient(name="Huile d'olive", quantity=6, unit="c.à.s"),
            Ingredient(name="Vinaigre de vin", quantity=2, unit="c.à.s"),
            Ingredient(name="Moutarde", quantity=1, unit="c.à.c"),
            Ingredient(name="Sel", quantity=1, unit="pincée"),
        ],
        steps=[
            "Délayer la moutarde avec le vinaigre et le sel.",
            "Verser l'huile en filet en fouettant jusqu'à émulsion.",
        ],
    ),
    RecipeCreate(
        name="Tartines avocat-oeuf",
        type="Petit-déj.",
        category="Été",
        servings=2,
        prep_minutes=10,
        cook_minutes=5,
        temperature="Chaud",
        ingredients=[
            Ingredient(name="Pain de campagne", quantity=2, unit="tranches"),
            Ingredient(name="Avocat", quantity=1, unit="u."),
            Ingredient(name="Oeufs", quantity=2, unit="u."),
            Ingredient(name="Citron", quantity=0.5, unit="u."),
        ],
        steps=[
            "Toaster le pain.",
            "Écraser l'avocat avec le jus de citron, saler.",
            "Pocher les oeufs 3 min, poser sur les tartines.",
        ],
    ),
]
